run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: leaderboard_system

issues:
  exclude:
    - "Error return value of .* is not checked"
  exclude-files:
    - ".*_test\\.go$"
