run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - revive
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - nakedret
    - prealloc
    - nolintlint
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: unexported-return
        disabled: true
  goimports:
    local-prefixes: leaderboard_system

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
