run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: leaderboard_system

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
