version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: leaderboard_system

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
